### ISSUE TITLE
Be clearer as to where to put files in hello world

### ISSUE THREAD

**Issue by quii** [quii/learn-go-with-tests#106]
Both @lnryan  and @shinyhappydan have mentioned how it is not clear _where_ the files should go for hello-world.

e.g `$GOPATH/src/github.com/{user}/hello`

Let's just add some text to explain that

**Comment by lnryan** [comment]
do go projects have any established practices for this, eg like npm's `package.json` that are best practices. it's interesting you directly mention `github.com/{user}/...` 

In my own stuff i tend to have `/repositories/{project}` and rely on the git init stuff to specify the particular remote source. I can see the advantage of making this transparent like above, but doesn't that also make it a bit harder to distinguish 'my' working files vs simply used ones? If I have some github hosted stuff and some gitlab hosted stuff, for instance, I'm now digging around in two different trees. 

I guess i'm asking if go has 'opinions' about that that are worth mentioning (rather than more generally how one organizes one's own code)

**Comment by quii** [comment]
Generally one puts go code inside 

$GOPATH/src/

You can set your own $GOPATH, but it'll default to `~/go` so for the sake of simplicity its easier just to stick with that

And usually you put the repo's URL sort of thing as the dir structure.

So this project on my computer is on `~/go/src/github.com/quii/learn-go-with-tests`

Basically all of Go's tooling works with this convention. It's often a point of friction for newcomers but the advice is always the same; just dont fight it :) 

There are options out there to fight it, but IMO it's just not worth it.

**Comment by lnryan** [comment]
nice.
