### ISSUE TITLE
100% test coverage add test for func main

### ISSUE THREAD

**Issue by amrboxit4me** [quii/learn-go-with-tests#144]
Hi 
How could I add a test case for func main so I get 100% test coverage?
I am using this plugin which shows errors and test coverage at status bar every time I save
https://marketplace.visualstudio.com/items?itemName=joaoacdias.golang-tdd

![screen shot 2018-12-24 at 5 32 42 pm](https://user-images.githubusercontent.com/41638061/50400663-f0a53a00-07a1-11e9-9d97-841ba260d07a.png)

**Comment by quii** [comment]
Hi

So broadly the best way to do this is to minimise the amount of code in `main`; so that you can test the rest. Even if you weren't testing its generally good practice to have very little code in `main`

e.g

```go
func main() {
    MyAmazingApp()
}
```

You can then test `MyAmazingApp` separately. 

As an aside, I wouldn't chase 100% test coverage too much. While coverage can be a helpful guide it can be totally abused into you writing tests that give you coverage but are actually annoying for maintainers going forward. 

[I cover this a bit in a talk I gave](http://www.quii.co.uk/The_Tests_Talk)
