### ISSUE TITLE
Select example: why can't I implicitly create the channel?

### ISSUE THREAD

**Issue by ohthehugemanatee** [quii/learn-go-with-tests#220]
In the Select example, I don't understand why it doesn't work if I create the channel implicitly in the `ping` function signature. Written [as given in the book](https://github.com/quii/learn-go-with-tests/blob/a5c02e44fa4a040a560f7da9526bbc898c195cef/select/v3/racer.go#L29) it works fine. But if I try:
```
func raceWebsite(url string) (ch chan bool) {
	go func() {
		http.Get(url)
		ch <- true
	}()
	return
}
```
the test eventually times out. What's the difference? Can we add some explanation, either in the return type doc or in channels? I feel like this is a "gotcha" that doesn't fit into my model of channels or return types.

**Comment by quii** [comment]
Hm, the important thing is the `make` part.

When you create variables by naming your return types it will default to the "zero" value of the type. So if it's a string it is `""`, if it's an int it's `0`. For channels it is `nil`. 

You cannot send data into nil channels and the `<-` operator will block until it can send data; which is why your test times out. 

This hopefully show's it a bit clearer

https://play.golang.org/p/IIbeAox5jKA

Does that clear it up?

Maybe the chapter could have a note about the zero values of channels and how they're typically not very useful?

**Comment by ohthehugemanatee** [comment]
Thank you for the explanation! Sorry for the late response, I only saw the email when you closed the issue. :| 

Anyway, yes it sounds like a good idea to include basically exactly that sentence: 
> When you create variables by naming your return types it will default to the "zero" value of the type. So if it's a string it is "", if it's an int it's 0. For channels it is nil.

Want me to submit a PR for it?
