### ISSUE TITLE
Select example: the program will wait all channel finish. it not return when the fast one finished

### ISSUE THREAD

**Issue by jackila** [quii/learn-go-with-tests#228]
when i change the select example ,make the delay time to 20 second.
![image](https://user-images.githubusercontent.com/32559813/63644855-8f64aa80-c724-11e9-9ef6-5ef74949f73d.png)
the test will take 20s to finish . 
but as the tutor , it should not,it should return as soon as the faster one finished 

but when i replace select with switch .it can return when the fast one finished
why?

**Comment by quii** [comment]
Strange, could you paste in your `Racer` code, it's a little unclear to me what's going on.

**Comment by jackila** [comment]
![image](https://user-images.githubusercontent.com/32559813/63661036-af12d600-c7eb-11e9-908d-219ee243405f.png)
actually ,the code is from your latest source code. and I just change the delay time 
my question is why the test will use 20s.
should it choose the fast one ,and will end faster than 20s?

**Comment by quii** [comment]
Ahh this is a good spot. 

In short, the code we have isn't best practice in some ways (for brevity). 

To see what's going on, put a print statement after the race in the test

```go
		got, err := Racer(slowURL, fastURL)

		fmt.Println("finished racing")
```

You should see that the "race" finishes and then you get a pause for a while and then the test finishes. 

What's happening is because the test server with a 20s timeout it is blocking our `Close()` call which is stopped the test from passing. There's a few things that you can do to make this code a little more robust to stop this

1. Don't use `http.Get`. That uses the default http client which has _no timeout_. In practice, you should always create your own (e.g `&http.Client{}`) and then configure it with the timeouts that you feel are sensible for your code.
2. What we should really do is redesign our code a bit so we can cancel the other http request once the other is done. That can be accomplished with `context.Context` (there's a chapter on that in this book). You can also see a more specific example here https://stackoverflow.com/a/29200933/3193

As I say, for brevity I'd rather not go into the specifics of this for this chapter but I think I may add a note to the end of the chapter just so people are aware of the shortcomings in the code. 

Hope my explanation clears things up

**Comment by jackila** [comment]
I got it .
thanks for u time

**Comment by kiesman99** [comment]
Hey there @quii,

First, thank you for this awesome guide! I am really enjoying reading through these chapters.

I've stumbled upon this issue too and the first thing I've done was looking into this repo and see if there's already an issue opened.

You think there is a possibility to link this issue in your guide?

Maybe in "Wrapping up" in a section called "drawbacks" or something.

Thanks again and have a nice day!

**Comment by alcalbg** [comment]
Instead of closing and shutting down the server, you can probably just close all open connections with:
```
 defer server.CloseClientConnections()
```
