### ISSUE TITLE
[sync] Unnecessary argument of anonymous function?

### ISSUE THREAD

**Issue by xuchunyang** [quii/learn-go-with-tests#269]
https://github.com/quii/learn-go-with-tests/blob/145aeaddec44bee51c83614170f1d820bb6c51f0/sync/v2/sync_test.go#L23-L32

In Line 27, does the anonymous function have to take `w *sync.WaitGroup`? It seems `wg` works fine from here:

```go
go func() {
	counter.Inc()
	defer wg.Done()
}()
```

**Comment by djangulo** [comment]
Hi.

It's good practice to pass a variable to the anonymous function when working with goroutines, otherwise you risk running into a race condition.

Calling goroutines in a loop without an explicit parameter causes all goroutines to work with the last value of the loop variable. Example:

```go
for i := 0; i < len(someSlice); i++ {
    go func() {
        // i gets modified by further iterations, all goroutines
        // are operating with i == len(someSlice)
        doThings(i)
    }()
}
```

You pass the variable to the anonymous function to prevent that

```go
for i := 0; i < len(someSlice); i++ {
    go func(i int) {
        // each goroutine gets a copy of i,
        // with the value of i when the `go` statement was executed
        doThings(i)
    }(i)
}
```

You got lucky. Your code works because of the nature of `sync.WaitGroup` (as it's a blocking mechanism itself).
