### ISSUE TITLE
"Hello world chapter" public vs private functions

### ISSUE THREAD

**Issue by roncromberge** [quii/learn-go-with-tests#354]
Hello,

At the end of this chapter you mention that private functions starts with a lowercase.
But the function **Hello** starts with a Capital and makes it public. Visualcode complains at it. That this function should be private! Because its not exported to the outside.

After refactor Hello to hello the complains are over.

I hope I'm right. I'm a go rookie :-)

Greetings Ron Cromberge

**Comment by quii** [comment]
Hi @roncromberge 

Sorry for the slow reply, end of the world and all that!

It's tricky because VS code is _kinda_ correct here, this function lives just in its own package and only consumed within it's own package so there's no need to be exported.

_However_, in practice you shouldn't generally test private (unexported) functions, for various reasons discussed in the book so I didn't want to start with that bad habit.

Hope that explains things!


Chris
