### ISSUE TITLE
Go Install Instructions for Windows / Ubuntu?

### ISSUE THREAD

**Issue by asheingold** [quii/learn-go-with-tests#406]
I'd be willing to create these but wanted to make sure if it'll be useful.

**Comment by quii** [comment]
In truth I'm tempted to remove the instructions for even OS X because I feel like setting up go

- Isn't the aim of the book
- Is well covered in other places
- Subtly changes over time which adds a needless maintenance overhead

So I'd say it's probably not worth your time, but thanks for bringing it up
