### ISSUE TITLE
Testing codebase depending on a third-party service

### ISSUE THREAD

**Issue by enkeyz** [quii/learn-go-with-tests#508]
How would you guys test a codebase - for example a discord bot - that depending on a third-party service - which is outside of your control? Mocking the service seems excessive, because it's just too complex. Some people suggested, that I should test against the real thing instead.

This function for example - where you query if a specific user has a permission in a discord server - needs a live discord session(provided by `*discordgo.Session` type):

```go
func HasPermissionInGuild(s *discordgo.Session, permission int64, guildID, userID string) (bool, error) {
        // get reference to the member with the given userID in the specifiy guild
	member, err := s.State.Member(guildID, userID)
	if err != nil {
		if member, err = s.GuildMember(guildID, userID); err != nil {
			return false, err
		}
	}
        
        // loop through the member's roles, and check if one of the roles has the given permission
	for _, roleID := range member.Roles {
		role, err := s.State.Role(guildID, roleID)
		if err != nil {
			return false, err
		}
		if role.Permissions&permission != 0 {
			return true, nil
		}
	}

	return false, nil
}
```

Suggestions are welcome.

**Comment by quii** [comment]
> Mocking the service seems excessive, because it's just too complex. Some people suggested, that I should test against the real thing instead.

IMO these people are close to the mark, but I like to setup my projects so that I'm not dependant on 3rd party systems if I can. I don't want my test suite slowed down or even breaking if another team that I can't control messes up.

How does their library work? Is it just some sugar around HTTP calls? If that's the case, you could mock it out with a fake API. 

As an aside, potentially you could redesign this so this is a method on a struct you define which has a `discordgo.Session` as a field. You'd then have a method `HasPermissionInGuild(permission int64, guildID, userID string) (bool, error)`. Whatever uses this thing could then define an interface more easily to test _that_ behaviour, without having to explicitly worry about discord sessions.
